services:
  netnotify-front-nginx:
  
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      - VITE_TINYMCE_API_KEY: ${VITE_TINYMCE_API_KEY}
      - VITE_KEYCLOAK_AUTH_SERVER: ${VITE_KEYCLOAK_AUTH_SERVER}
      - VITE_KEYCLOAK_URL_REDIRECT: ${VITE_KEYCLOAK_URL_REDIRECT}
      - VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID}
      - VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_SECRET: ${VITE_KEYCLOAK_SECRET}
      - VITE_ROLE_ADMIN: ${VITE_ROLE_ADMIN}
      - VITE_ROLE_USER: ${VITE_ROLE_USER}

